"""Pure builders for derived content — corpus/manifest in, markdown/dict out.

No I/O. commands/derived.py does the file writing. Mirrors the marker-region
idea from patch/toml_nav.py, but with HTML comments for markdown.
"""
import re

DASH_BEGIN = "<!-- >>> ZPLUS_DASHBOARD — generated by zplus; edits below are overwritten >>> -->"
DASH_END = "<!-- <<< ZPLUS_DASHBOARD <<< -->"


def splice_md_region(text, begin, end, body):
    """Insert or replace a marker-delimited region. Idempotent."""
    region = begin + "\n\n" + body + "\n\n" + end
    if begin in text and end in text:
        pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
        return pat.sub(lambda _: region, text)
    sep = "" if text.endswith("\n") else "\n"
    return text + sep + "\n" + region + "\n"


def _as_list(value):
    if value is None or value == []:
        return []
    return value if isinstance(value, list) else [value]


def _fmt(value):
    return ", ".join(str(v) for v in _as_list(value))


def dashboard_table(doc_type, entries, corpus):
    """Markdown table: Entry link + one column per declared field + inbound count."""
    names = [f.name for f in doc_type.fields]
    header = ["Entry"] + names + ["Referenced by"]
    rows = ["| " + " | ".join(header) + " |",
            "| " + " | ".join(["---"] * len(header)) + " |"]
    for e in sorted(entries, key=lambda e: e.slug):
        inbound = sum(len(v) for v in e.backlinks.values())
        cells = [f"[{e.title}]({e.slug}.md)"]
        cells += [_fmt(e.fields.get(n)) for n in names]
        cells += [str(inbound) if inbound else ""]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)
