"""Pure builders for derived content — corpus/manifest in, markdown/dict out.

No I/O. commands/derived.py does the file writing. Mirrors the marker-region
idea from patch/toml_nav.py, but with HTML comments for markdown.
"""
import re

DASH_BEGIN = "<!-- >>> ZPLUS_DASHBOARD — generated by zplus; edits below are overwritten >>> -->"
DASH_END = "<!-- <<< ZPLUS_DASHBOARD <<< -->"


def splice_md_region(text, begin, end, body):
    """Insert or replace a marker-delimited region. Idempotent."""
    region = begin + "\n\n" + body + "\n\n" + end
    if begin in text and end in text:
        pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
        return pat.sub(lambda _: region, text)
    sep = "" if text.endswith("\n") else "\n"
    return text + sep + "\n" + region + "\n"


def _as_list(value):
    if value is None or value == []:
        return []
    return value if isinstance(value, list) else [value]


def _fmt(value):
    return ", ".join(str(v) for v in _as_list(value))


def dashboard_table(doc_type, entries, corpus):
    """Markdown table: Entry link + one column per declared field + inbound count."""
    names = [f.name for f in doc_type.fields]
    header = ["Entry"] + names + ["Referenced by"]
    rows = ["| " + " | ".join(header) + " |",
            "| " + " | ".join(["---"] * len(header)) + " |"]
    for e in sorted(entries, key=lambda e: e.slug):
        inbound = sum(len(v) for v in e.backlinks.values())
        cells = [f"[{e.title}]({e.slug}.md)"]
        cells += [_fmt(e.fields.get(n)) for n in names]
        cells += [str(inbound) if inbound else ""]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def _bullet_lines(items):
    return "\n".join(items) if items else "_None._"


def _status_field(doc_type):
    return next((f for f in doc_type.fields if f.type == "status"), None)


def action_center_markdown(corpus, m):
    """A generated worklist: unowned, open-status, and dangling-ref entries.

    "Open" means a type whose status field declares `done` has an entry whose
    status is not among those done states — read from the workflow, not guessed.
    """
    type_by_name = {t.name: t for t in m.types}
    unowned, open_items, dangling = [], [], []
    for e in corpus.entries:
        t = type_by_name.get(e.type_name)
        if not t:
            continue
        link = f"../{t.folder}/{e.slug}.md"
        ref = f"[{e.title}]({link})"
        if any(f.name == "owner" and f.required for f in t.fields) \
                and not e.fields.get("owner"):
            unowned.append(f"- {ref} — no owner")
        sf = _status_field(t)
        status = e.fields.get("status")
        if sf and sf.done and status and status not in sf.done:
            open_items.append(f"- {ref} — status `{status}`")
        for f in t.fields:
            if f.type != "ref":
                continue
            for slug in _as_list(e.fields.get(f.name)):
                if slug and slug not in corpus.by_slug:
                    dangling.append(f"- {ref} — `{f.name}` → missing `{slug}`")
    return (
        "<!-- generated by zplus gen-derived; edits are overwritten -->\n"
        "# Action Center\n\n"
        "What needs attention across the company, derived from every entry.\n\n"
        "## Needs an owner\n\n" + _bullet_lines(unowned) + "\n\n"
        "## Open / in progress\n\n" + _bullet_lines(open_items) + "\n\n"
        "## Broken links\n\n" + _bullet_lines(dangling) + "\n"
    )


BOARD_BEGIN = "<!-- >>> ZPLUS_BOARD — generated by zplus; edits below are overwritten >>> -->"
BOARD_END = "<!-- <<< ZPLUS_BOARD <<< -->"
FACET_BEGIN = "<!-- >>> ZPLUS_FACET — generated by zplus; edits below are overwritten >>> -->"
FACET_END = "<!-- <<< ZPLUS_FACET <<< -->"


def render_grouped(entries, groups, group_of, empty="_None._"):
    """Markdown: a '### group' section per group with a bullet list of entry links.

    groups: ordered group labels. group_of: entry -> its group label.
    """
    buckets = {g: [] for g in groups}
    for e in sorted(entries, key=lambda e: e.slug):
        g = group_of(e)
        if g in buckets:
            buckets[g].append(f"- [{e.title}]({e.slug}.md)")
    out = []
    for g in groups:
        out.append(f"### {g}\n")
        out.append("\n".join(buckets[g]) if buckets[g] else empty)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def status_diagram(status_field):
    """A mermaid stateDiagram of a status workflow (values in order)."""
    vals = status_field.values
    lines = ["```mermaid", "stateDiagram-v2"]
    if vals:
        lines.append(f"  [*] --> {vals[0]}")
    for a, b in zip(vals, vals[1:]):
        lines.append(f"  {a} --> {b}")
    for v in status_field.done:
        lines.append(f"  {v} --> [*]")
    lines.append("```")
    return "\n".join(lines)


def board_markdown(doc_type, entries):
    """Kanban-by-status: a column per status value in workflow order + a state diagram."""
    sf = _status_field(doc_type)
    if not sf:
        return ""
    body = render_grouped(entries, sf.values, lambda e: e.fields.get("status"))
    return "## Board\n\n" + body + "\n" + status_diagram(sf)


def facet_markdown(doc_type, entries):
    """Group the collection by its facet field's values."""
    fld = next((f for f in doc_type.fields if f.name == doc_type.facet), None)
    if not fld:
        return ""
    groups = list(fld.values) + ["(unset)"]
    body = render_grouped(entries, groups,
                          lambda e: e.fields.get(doc_type.facet) or "(unset)")
    return f"## By {doc_type.facet}\n\n" + body


def _node_id(slug):
    return re.sub(r"[^0-9A-Za-z_]", "_", slug)


def graph_mermaid(corpus, m):
    """A mermaid graph of the corpus: a node per ref-connected entry, edge per ref."""
    type_by_name = {t.name: t for t in m.types}
    nodes, edges = {}, []
    for e in corpus.entries:
        t = type_by_name.get(e.type_name)
        if not t:
            continue
        for f in t.fields:
            if f.type != "ref":
                continue
            for slug in _as_list(e.fields.get(f.name)):
                tgt = corpus.by_slug.get(slug)
                if tgt is None:
                    continue
                nodes[e.slug] = e.title
                nodes[tgt.slug] = tgt.title
                edges.append((e.slug, f.name, tgt.slug))
    lines = ["```mermaid", "graph LR"]
    for slug, title in sorted(nodes.items()):
        lines.append(f'  {_node_id(slug)}["{title}"]')
    for src, field_name, tgt in edges:
        lines.append(f"  {_node_id(src)} -->|{field_name}| {_node_id(tgt)}")
    lines.append("```")
    return "\n".join(lines)


def llms_txt(corpus, m):
    """A plain-text index for agents (llms.txt convention), pointing at corpus.json."""
    by_type = {}
    for e in corpus.entries:
        by_type.setdefault(e.type_name, []).append(e)
    lines = ["# zplus site — machine-readable index", "",
             "Structured data for every entry (fields + resolved refs + backlinks): "
             "./corpus.json", ""]
    for t in m.types:
        ents = by_type.get(t.name)
        if not ents:
            continue
        lines.append(f"## {t.label}")
        for e in sorted(ents, key=lambda e: e.slug):
            lines.append(f"- {e.title} ({t.folder}/{e.slug}.md)")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def corpus_to_dict(corpus):
    return {"entries": [
        {"type": e.type_name, "slug": e.slug, "title": e.title,
         "fields": e.fields,
         "backlinks": {f"{k[0]}.{k[1]}": v for k, v in e.backlinks.items()}}
        for e in corpus.entries
    ]}
